{% set name = "ria" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ria-{{ version }}.tar.gz
  sha256: d32879a4e1b3e102fc5d65338f623764fbfb197570e536a5dfd57197aeec74c5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - meow = cli.meow:script_entry

requirements:
  host:
    - python >=3.11
    - pip
  run:
    - python >=3.11

test:
  imports:
    - ria
  commands:
    - pip check
    - meow --help
  requires:
    - pip

about:
  home: https://github.com/qoherent/ria
  summary: Radio Intelligence Apps' open-source core, by Qoherent
  description: |
    Stay tuned for the upcoming release of Radio Intelligence Apps by Qoherent!
  license: GPL-3.0-only
  license_file: LICENSE
  dev_url: https://github.com/qoherent/ria

extra:
  recipe-maintainers:
    - mrl280
